In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Student.csv')
df=pd.DataFrame(df)
df

,Student_ID,Age,Gender,Attendance_Percent,Study_Hours_Per_Day,Assignment_Score,Midterm_Score,Final_Exam_Score,Result
0,101,20,Male,92,3.5,88,84,90,Pass
1,102,21,Female,85,2.0,76,70,74,Pass
2,103,19,Male,78,1.5,65,62,68,Pass
3,104,22,Female,88,4.0,91,89,92,Pass
4,105,20,Male,95,5.0,95,93,97,Pass
5,106,21,Female,81,2.5,72,75,78,Pass
6,107,23,Male,76,1.0,60,58,61,Pass
7,108,20,Female,90,3.0,85,87,89,Pass
8,109,22,Male,84,2.2,79,74,80,Pass
9,110,19,Female,97,5.5,98,96,99,Pass

In [4]:
print("Type:", type(df))
print("Columns:", list(df.columns))
print("Index:", df.index.tolist())
df

Type: <class 'pandas.DataFrame'>
Columns: ['Student_ID', 'Age', 'Gender', 'Attendance_Percent', 'Study_Hours_Per_Day', 'Assignment_Score', 'Midterm_Score', 'Final_Exam_Score', 'Result']
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

,Student_ID,Age,Gender,Attendance_Percent,Study_Hours_Per_Day,Assignment_Score,Midterm_Score,Final_Exam_Score,Result
0,101,20,Male,92,3.5,88,84,90,Pass
1,102,21,Female,85,2.0,76,70,74,Pass
2,103,19,Male,78,1.5,65,62,68,Pass
3,104,22,Female,88,4.0,91,89,92,Pass
4,105,20,Male,95,5.0,95,93,97,Pass
5,106,21,Female,81,2.5,72,75,78,Pass
6,107,23,Male,76,1.0,60,58,61,Pass
7,108,20,Female,90,3.0,85,87,89,Pass
8,109,22,Male,84,2.2,79,74,80,Pass
9,110,19,Female,97,5.5,98,96,99,Pass

In [5]:
print("First 3 rows:")
display(df.head(3))

print("\nLast 3 rows:")
display(df.tail(3))

print("\nInfo:")
df.info()

print("\nDescribe:")
display(df.describe())

print("\nShape (rows, columns):", df.shape)

First 3 rows:

,Student_ID,Age,Gender,Attendance_Percent,Study_Hours_Per_Day,Assignment_Score,Midterm_Score,Final_Exam_Score,Result
0,101,20,Male,92,3.5,88,84,90,Pass
1,102,21,Female,85,2.0,76,70,74,Pass
2,103,19,Male,78,1.5,65,62,68,Pass

Last 3 rows:

,Student_ID,Age,Gender,Attendance_Percent,Study_Hours_Per_Day,Assignment_Score,Midterm_Score,Final_Exam_Score,Result
7,108,20,Female,90,3.0,85,87,89,Pass
8,109,22,Male,84,2.2,79,74,80,Pass
9,110,19,Female,97,5.5,98,96,99,Pass

Info:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student_ID           10 non-null     int64
 1   Age                  10 non-null     int64
 2   Gender               10 non-null     str
 3   Attendance_Percent   10 non-null     int64
 4   Study_Hours_Per_Day  10 non-null     float64
 5   Assignment_Score     10 non-null     int64
 6   Midterm_Score        10 non-null     int64
 7   Final_Exam_Score     10 non-null     int64
 8   Result               10 non-null     str
dtypes: float64(1), int64(6), str(2)
memory usage: 852.0 bytes

Describe:

,Student_ID,Age,Attendance_Percent,Study_Hours_Per_Day,Assignment_Score,Midterm_Score,Final_Exam_Score
count,10.00000,10.000000,10.000000,10.000000,10.00000,10.000000,10.000000
mean,105.50000,20.700000,86.600000,3.020000,80.90000,78.800000,82.800000
std,3.02765,1.337494,7.058486,1.477084,12.72312,13.019643,12.656136
min,101.00000,19.000000,76.000000,1.000000,60.00000,58.000000,61.000000
25%,103.25000,20.000000,81.750000,2.050000,73.00000,71.000000,75.000000
50%,105.50000,20.500000,86.500000,2.750000,82.00000,79.500000,84.500000
75%,107.75000,21.750000,91.500000,3.875000,90.25000,88.500000,91.500000
max,110.00000,23.000000,97.000000,5.500000,98.00000,96.000000,99.000000

Shape (rows, columns): (10, 9)

In [7]:
# loc: label-based selection
print("loc example (rows 0-2, specific columns):")
display(df.loc[0:2, ["Age", "Attendance_Percent", "Assignment_Score"]])

# iloc: position-based selection
print("\niloc example (first 3 rows, first 3 columns):")
display(df.iloc[0:3, 0:3])

# Boolean indexing: filter rows where Region is 'East'
print("\nBoolean indexing (Region == 'East'):")
display(df[df["Gender"] == "Male"])

loc example (rows 0-2, specific columns):

   Age  Attendance_Percent  Assignment_Score
0   20                  92                88
1   21                  85                76
2   19                  78                65

iloc example (first 3 rows, first 3 columns):

   Student_ID  Age  Gender
0         101   20    Male
1         102   21  Female
2         103   19    Male

Boolean indexing (Region == 'East'):

,Student_ID,Age,Gender,Attendance_Percent,Study_Hours_Per_Day,Assignment_Score,Midterm_Score,Final_Exam_Score,Result
0,101,20,Male,92,3.5,88,84,90,Pass
2,103,19,Male,78,1.5,65,62,68,Pass
4,105,20,Male,95,5.0,95,93,97,Pass
6,107,23,Male,76,1.0,60,58,61,Pass
8,109,22,Male,84,2.2,79,74,80,Pass

In [9]:
df=pd.read_excel('Student.xlsx')
df=pd.DataFrame(df)
df

NameError: name 'pd' is not defined